# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  slaballocator_config = debug
  slabtests_config = debug
  bench_config = debug

else ifeq ($(config),release)
  slaballocator_config = release
  slabtests_config = release
  bench_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := slaballocator slabtests bench

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

slaballocator:
ifneq (,$(slaballocator_config))
	@echo "==== Building slaballocator ($(slaballocator_config)) ===="
	@${MAKE} --no-print-directory -C slab_allocator -f Makefile config=$(slaballocator_config)
endif

slabtests: slaballocator
ifneq (,$(slabtests_config))
	@echo "==== Building slabtests ($(slabtests_config)) ===="
	@${MAKE} --no-print-directory -C slab_tests -f Makefile config=$(slabtests_config)
endif

bench: slaballocator
ifneq (,$(bench_config))
	@echo "==== Building bench ($(bench_config)) ===="
	@${MAKE} --no-print-directory -C slab_bench -f Makefile config=$(bench_config)
endif

clean:
	@${MAKE} --no-print-directory -C slab_allocator -f Makefile clean
	@${MAKE} --no-print-directory -C slab_tests -f Makefile clean
	@${MAKE} --no-print-directory -C slab_bench -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   slaballocator"
	@echo "   slabtests"
	@echo "   bench"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"